/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDayDateRouteImport } from './routes/_authenticated/day.$date'
import { Route as AuthenticatedEntriesNewRouteImport } from './routes/_authenticated/entries.new'
import { Route as AuthenticatedEntriesIdEditRouteImport } from './routes/_authenticated/entries.$id.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDayDateRoute = AuthenticatedDayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntriesNewRoute = AuthenticatedEntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntriesIdEditRoute =
  AuthenticatedEntriesIdEditRouteImport.update({
    id: '/entries/$id/edit',
    path: '/entries/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/day/$date': typeof AuthenticatedDayDateRoute
  '/entries/new': typeof AuthenticatedEntriesNewRoute
  '/entries/$id/edit': typeof AuthenticatedEntriesIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/day/$date': typeof AuthenticatedDayDateRoute
  '/entries/new': typeof AuthenticatedEntriesNewRoute
  '/entries/$id/edit': typeof AuthenticatedEntriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/day/$date': typeof AuthenticatedDayDateRoute
  '/_authenticated/entries/new': typeof AuthenticatedEntriesNewRoute
  '/_authenticated/entries/$id/edit': typeof AuthenticatedEntriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/day/$date' | '/entries/new' | '/entries/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/day/$date' | '/entries/new' | '/entries/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/day/$date'
    | '/_authenticated/entries/new'
    | '/_authenticated/entries/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/day/$date': {
      id: '/_authenticated/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof AuthenticatedDayDateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entries/new': {
      id: '/_authenticated/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof AuthenticatedEntriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entries/$id/edit': {
      id: '/_authenticated/entries/$id/edit'
      path: '/entries/$id/edit'
      fullPath: '/entries/$id/edit'
      preLoaderRoute: typeof AuthenticatedEntriesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDayDateRoute: typeof AuthenticatedDayDateRoute
  AuthenticatedEntriesNewRoute: typeof AuthenticatedEntriesNewRoute
  AuthenticatedEntriesIdEditRoute: typeof AuthenticatedEntriesIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDayDateRoute: AuthenticatedDayDateRoute,
  AuthenticatedEntriesNewRoute: AuthenticatedEntriesNewRoute,
  AuthenticatedEntriesIdEditRoute: AuthenticatedEntriesIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
